# Generated by Django 5.0.3 on 2024-03-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.BooleanField(default=False)),
                ('botao', models.BooleanField(default=False)),
                ('ligaRobo', models.BooleanField(default=False)),
                ('resetContador', models.BooleanField(default=False)),
                ('valorContagem', models.IntegerField(default=0)),
            ],
        ),
    ]
